### ISSUE TITLE
Importing OpenCV fails on linux/arm64 host. 

### ISSUE THREAD

**Issue by dennis-glx** [antaris-inc/SatOS-Payload-Demos#1] opened 2023-08-16 07:21 UTC
Hi, 

I was trying to build the python payload app demo using the instructions from the README. (master: 95e0731b20b1f3f5a1a762f4de8ec3324cae5646)

I've changed the platform option here from amd64 to arm64 to run natively on my M1 Macbook. 
```bash
docker build  --platform=linux/arm64 -t python-imager .
```

The build succeeds, but it fails on attempting to import OpenCV. I've substituted the actual remote config .zip file name with ```config_1234``` for brevity. 

```bash
$ docker run --platform=linux/arm64 -e CONFIG=_Packages_upload_config_1234.zip -v $(pwd):/workspace -v $(pwd)/outbound:/opt/antaris/outbound -it python-imager

Archive:  /workspace/_Packages_upload_config_1234.zip
  inflating: config_1234.deb
  inflating: README.md
Selecting previously unselected package config_1234.
(Reading database ... 39430 files and directories currently installed.)
Preparing to unpack config_1234.deb ...
Unpacking config_1234 (0.1) ...
Setting up config_1234 (0.1) ...
Traceback (most recent call last):
  File "/opt/antaris/app/src/app.py", line 27, in <module>
    import imager
  File "/opt/antaris/app/src/imager.py", line 19, in <module>
    import cv2
  File "/usr/local/lib/python3.10/dist-packages/cv2/__init__.py", line 181, in <module>
    bootstrap()
  File "/usr/local/lib/python3.10/dist-packages/cv2/__init__.py", line 175, in bootstrap
    if __load_extra_py_code_for_module("cv2", submodule, DEBUG):
  File "/usr/local/lib/python3.10/dist-packages/cv2/__init__.py", line 28, in __load_extra_py_code_for_module
    py_module = importlib.import_module(module_name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/local/lib/python3.10/dist-packages/cv2/typing/__init__.py", line 69, in <module>
    NumPyArrayGeneric = numpy.ndarray[typing.Any, numpy.dtype[numpy.generic]]
TypeError: 'numpy._DTypeMeta' object is not subscriptable
```

Possible reason for import failure in OpenCV. Wasn't able to find a matching open issue on the OpenCV repo. 
https://stackoverflow.com/questions/68916893/typeerror-numpy-dtypemeta-object-is-not-subscriptable

Minimal app.py to reproduce
```
import datetime
import json
import logging
import pathlib
import os
import signal
import sys
import time

from satos_payload_sdk import app_framework

# This import imports OpenCV internally.
import imager
```

**Comment by rahulbhivare** [comment] 2023-08-17 07:31
Hi,
    The issue is resolved in latest commit. You need to pull latest updates in master branch.
    Thank you.
Regards,
Rahul

**Closed by rahulbhivare** 2023-08-17 07:31 UTC
